"""empty message

Revision ID: bff25f197950
Revises: 
Create Date: 2022-12-29 00:30:23.012502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff25f197950'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('net_fee', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_process_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_process_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.DateTime(), nullable=False),
    sa.Column('submitted_procedure', sa.String(), nullable=False),
    sa.Column('quadrant', sa.String(), nullable=True),
    sa.Column('plan_group_no', sa.String(), nullable=False),
    sa.Column('subscriber_no', sa.String(), nullable=False),
    sa.Column('provider_npi', sa.String(), nullable=False),
    sa.Column('provider_fee', sa.Float(), nullable=False),
    sa.Column('allowed_fee', sa.Float(), nullable=False),
    sa.Column('member_coinsurance', sa.Float(), nullable=False),
    sa.Column('member_copay', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['claim_process_id'], ['claim_processes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_process_items')
    op.drop_table('claim_processes')
    # ### end Alembic commands ###
